import type { StructuredFormSection } from "./components/StructuredQuickForm";

export const propertyFormSections: StructuredFormSection[] = [
  {
    title: "Identificazione",
    description: "Riferimenti interni e classificazione principale dell’immobile.",
    fields: [
      { name: "referenceCode", label: "Riferimento", placeholder: "Generato automaticamente se vuoto" },
      {
        name: "managementType",
        label: "Tipo gestione",
        type: "select",
        required: true,
        options: ["Vendita", "Affitto", "Vendita e affitto", "Asta"],
      },
      {
        name: "propertyType",
        label: "Tipologia",
        type: "select",
        required: true,
        options: ["Appartamento", "Attico", "Villa", "Casa indipendente", "Rustico", "Box", "Negozio", "Ufficio", "Capannone", "Terreno", "Altro"],
      },
      { name: "title", label: "Titolo scheda", required: true, wide: true },
      {
        name: "commercialStatus",
        label: "Stato commerciale",
        type: "select",
        options: ["Bozza", "Notizia", "In valutazione", "In acquisizione", "In gestione", "Sospeso", "In trattativa", "Venduto", "Affittato", "Archiviato"],
      },
      { name: "assignedAgent", label: "Agente assegnato" },
      { name: "acquisitionSource", label: "Provenienza acquisizione" },
    ],
  },
  {
    title: "Dati commerciali",
    description: "Prezzi, incarico e condizioni economiche della proposta.",
    fields: [
      { name: "askingPrice", label: "Prezzo richiesto", type: "number", required: true },
      { name: "minimumPrice", label: "Prezzo minimo concordato", type: "number" },
      { name: "monthlyRent", label: "Canone mensile", type: "number" },
      { name: "condominiumFees", label: "Spese condominiali mensili", type: "number" },
      { name: "ownerName", label: "Proprietario", required: true, wide: true },
      { name: "ownerPhone", label: "Telefono proprietario", type: "tel" },
      { name: "ownerTaxCode", label: "Codice fiscale proprietario" },
      {
        name: "mandateType",
        label: "Tipo incarico",
        type: "select",
        options: ["Da definire", "Esclusiva", "Non esclusiva", "Collaborazione", "Segnalazione"],
      },
      { name: "mandateStartDate", label: "Inizio incarico", type: "date" },
      { name: "mandateEndDate", label: "Scadenza incarico", type: "date" },
      { name: "commissionTerms", label: "Condizioni provvigionali", wide: true },
      {
        name: "occupancyStatus",
        label: "Occupazione",
        type: "select",
        options: ["Non indicato", "Libero", "Occupato dal proprietario", "Locato", "In liberazione"],
      },
      { name: "availabilityDate", label: "Disponibile dal", type: "date" },
    ],
  },
  {
    title: "Indirizzi",
    description: "Ubicazione completa e indicazioni da usare nella pubblicazione.",
    fields: [
      { name: "country", label: "Paese", placeholder: "Italia" },
      { name: "region", label: "Regione" },
      { name: "province", label: "Provincia" },
      { name: "municipality", label: "Comune", required: true },
      { name: "district", label: "Zona o quartiere" },
      { name: "street", label: "Via o piazza", required: true, wide: true },
      { name: "streetNumber", label: "Civico", required: true },
      { name: "postalCode", label: "CAP" },
      { name: "buildingName", label: "Palazzo o complesso" },
      { name: "staircase", label: "Scala" },
      { name: "internalNumber", label: "Interno" },
      { name: "latitude", label: "Latitudine", type: "number" },
      { name: "longitude", label: "Longitudine", type: "number" },
      { name: "hideExactAddress", label: "Nascondi indirizzo esatto negli annunci", type: "checkbox", wide: true },
    ],
  },
  {
    title: "Caratteristiche",
    description: "Consistenze, distribuzione e dotazioni principali.",
    fields: [
      { name: "commercialArea", label: "Superficie commerciale (m²)", type: "number", required: true },
      { name: "walkableArea", label: "Superficie calpestabile (m²)", type: "number" },
      { name: "rooms", label: "Locali", type: "number" },
      { name: "bedrooms", label: "Camere", type: "number" },
      { name: "bathrooms", label: "Bagni", type: "number" },
      { name: "floor", label: "Piano" },
      { name: "totalFloors", label: "Piani edificio", type: "number" },
      { name: "constructionYear", label: "Anno costruzione", type: "number" },
      {
        name: "condition",
        label: "Stato conservazione",
        type: "select",
        options: ["Nuovo", "Ottimo", "Buono", "Abitabile", "Da ristrutturare", "In costruzione"],
      },
      {
        name: "furnishing",
        label: "Arredamento",
        type: "select",
        options: ["Non indicato", "Arredato", "Parzialmente arredato", "Non arredato"],
      },
      {
        name: "heatingType",
        label: "Riscaldamento",
        type: "select",
        options: ["Assente", "Autonomo", "Centralizzato", "Pompa di calore", "Altro"],
      },
      { name: "hasElevator", label: "Ascensore", type: "checkbox" },
      { name: "hasBalcony", label: "Balcone", type: "checkbox" },
      { name: "hasTerrace", label: "Terrazzo", type: "checkbox" },
      { name: "hasGarden", label: "Giardino", type: "checkbox" },
      { name: "hasGarage", label: "Garage o box", type: "checkbox" },
      { name: "hasParkingSpace", label: "Posto auto", type: "checkbox" },
      { name: "hasCellar", label: "Cantina", type: "checkbox" },
      { name: "accessories", label: "Altri accessori", placeholder: "Portineria, piscina, allarme…", wide: true },
      { name: "propertyDescription", label: "Descrizione completa", type: "textarea", wide: true },
    ],
  },
  {
    title: "Catasto ed energia",
    description: "Riferimenti catastali, conformità e prestazione energetica.",
    fields: [
      { name: "landRegistryMunicipality", label: "Comune catastale" },
      { name: "cadastralSheet", label: "Foglio" },
      { name: "cadastralParcel", label: "Particella" },
      { name: "cadastralSubaltern", label: "Subalterno" },
      { name: "cadastralCategory", label: "Categoria catastale" },
      { name: "cadastralRooms", label: "Vani catastali", type: "number" },
      { name: "cadastralIncome", label: "Rendita catastale", type: "number" },
      {
        name: "cadastralCompliance",
        label: "Conformità catastale",
        type: "select",
        options: ["Da verificare", "Conforme", "Non conforme", "In regolarizzazione"],
      },
      {
        name: "urbanPlanningCompliance",
        label: "Conformità urbanistica",
        type: "select",
        options: ["Da verificare", "Conforme", "Non conforme", "In regolarizzazione"],
      },
      {
        name: "energyClass",
        label: "Classe energetica",
        type: "select",
        options: ["Non disponibile", "A4", "A3", "A2", "A1", "B", "C", "D", "E", "F", "G", "Esente"],
      },
      { name: "energyPerformanceIndex", label: "Indice prestazione energetica", type: "number" },
      { name: "energyCertificateExpiry", label: "Scadenza APE", type: "date" },
    ],
  },
  {
    title: "Pubblicazione e asta",
    description: "Visibilità dell’annuncio e dati specifici per eventuali procedure d’asta.",
    fields: [
      { name: "publishOnWebsite", label: "Pubblica sul sito", type: "checkbox" },
      { name: "publishOnPortals", label: "Pubblica sui portali", type: "checkbox" },
      { name: "featuredListing", label: "Metti in evidenza", type: "checkbox" },
      { name: "isOpportunity", label: "Segnala come occasione", type: "checkbox" },
      { name: "publicationStartDate", label: "Inizio pubblicazione", type: "date" },
      { name: "publicationEndDate", label: "Fine pubblicazione", type: "date" },
      { name: "publicHeadline", label: "Titolo pubblico", wide: true },
      { name: "publicDescription", label: "Descrizione pubblica", type: "textarea", wide: true },
      { name: "isAuction", label: "Immobile in asta", type: "checkbox" },
      { name: "courtName", label: "Tribunale" },
      { name: "procedureNumber", label: "Numero procedura" },
      { name: "auctionBasePrice", label: "Prezzo base asta", type: "number" },
      { name: "minimumBid", label: "Offerta minima", type: "number" },
      { name: "auctionDate", label: "Data asta", type: "date" },
      { name: "auctionTime", label: "Ora asta", type: "time" },
      { name: "auctionNotes", label: "Note procedura", type: "textarea", wide: true },
    ],
  },
];

export const propertyFilterSections: StructuredFormSection[] = [
  {
    title: "Ricerca immobile",
    fields: [
      { name: "referenceCode", label: "Riferimento" },
      { name: "title", label: "Titolo o indirizzo", wide: true },
      {
        name: "managementType",
        label: "Tipo gestione",
        type: "select",
        options: ["", "Vendita", "Affitto", "Vendita e affitto", "Asta"],
      },
      {
        name: "propertyType",
        label: "Tipologia",
        type: "select",
        options: ["", "Appartamento", "Attico", "Villa", "Casa indipendente", "Rustico", "Box", "Negozio", "Ufficio", "Capannone", "Terreno", "Altro"],
      },
      {
        name: "commercialStatus",
        label: "Stato commerciale",
        type: "select",
        options: ["", "Bozza", "Notizia", "In valutazione", "In acquisizione", "In gestione", "Sospeso", "In trattativa", "Venduto", "Affittato", "Archiviato"],
      },
      { name: "assignedAgent", label: "Agente" },
    ],
  },
  {
    title: "Zona e valori",
    fields: [
      { name: "municipality", label: "Comune" },
      { name: "district", label: "Zona" },
      { name: "street", label: "Via" },
      { name: "minimumPrice", label: "Prezzo minimo", type: "number" },
      { name: "maximumPrice", label: "Prezzo massimo", type: "number" },
      { name: "minimumArea", label: "Superficie minima", type: "number" },
      { name: "maximumArea", label: "Superficie massima", type: "number" },
      { name: "minimumRooms", label: "Locali minimi", type: "number" },
      { name: "isAuction", label: "Solo aste", type: "checkbox" },
      { name: "publishedOnly", label: "Solo pubblicati", type: "checkbox" },
    ],
  },
  {
    title: "Catasto e proprietario",
    fields: [
      { name: "ownerName", label: "Proprietario" },
      { name: "ownerPhone", label: "Telefono proprietario", type: "tel" },
      { name: "cadastralSheet", label: "Foglio" },
      { name: "cadastralParcel", label: "Particella" },
      { name: "cadastralSubaltern", label: "Subalterno" },
      { name: "cadastralCategory", label: "Categoria catastale" },
      {
        name: "energyClass",
        label: "Classe energetica",
        type: "select",
        options: ["", "A4", "A3", "A2", "A1", "B", "C", "D", "E", "F", "G", "Esente"],
      },
    ],
  },
];

export const contactFormSections: StructuredFormSection[] = [
  {
    title: "Anagrafica",
    description: "Identità della persona o dell’organizzazione.",
    fields: [
      { name: "firstName", label: "Nome", required: true },
      { name: "lastName", label: "Cognome", required: true },
      { name: "companyName", label: "Azienda o ragione sociale", wide: true },
      { name: "taxCode", label: "Codice fiscale" },
      { name: "vatNumber", label: "Partita IVA" },
      { name: "birthDate", label: "Data di nascita", type: "date" },
      { name: "birthPlace", label: "Luogo di nascita" },
      {
        name: "contactKind",
        label: "Tipo anagrafica",
        type: "select",
        options: ["Persona fisica", "Azienda", "Ente", "Professionista"],
      },
      { name: "nationality", label: "Cittadinanza" },
      { name: "preferredLanguage", label: "Lingua preferita" },
    ],
  },
  {
    title: "Ruoli e gestione",
    description: "Ruolo commerciale, provenienza e responsabilità interna.",
    fields: [
      {
        name: "primaryRole",
        label: "Ruolo principale",
        type: "select",
        required: true,
        options: ["Generico", "Proprietario", "Acquirente", "Locatore", "Locatario", "Inserzionista", "Segnalatore", "Professionista"],
      },
      { name: "additionalRoles", label: "Altri ruoli", placeholder: "Separare i ruoli con una virgola", wide: true },
      {
        name: "contactStatus",
        label: "Stato",
        type: "select",
        options: ["Nuovo", "Da qualificare", "Attivo", "Da ricontattare", "Non interessato", "Sospeso", "Archiviato"],
      },
      { name: "acquisitionSource", label: "Provenienza" },
      { name: "assignedAgent", label: "Operatore assegnato" },
      { name: "acquisitionDate", label: "Data acquisizione", type: "date" },
      { name: "tags", label: "Etichette", placeholder: "Es. investitore, prima casa, urgente", wide: true },
    ],
  },
  {
    title: "Recapiti",
    description: "Recapiti multipli e preferenze di contatto.",
    fields: [
      { name: "primaryPhone", label: "Telefono principale", type: "tel", required: true },
      { name: "secondaryPhone", label: "Telefono secondario", type: "tel" },
      { name: "workPhone", label: "Telefono lavoro", type: "tel" },
      { name: "primaryEmail", label: "Email principale", type: "email" },
      { name: "secondaryEmail", label: "Email secondaria", type: "email" },
      { name: "certifiedEmail", label: "PEC", type: "email" },
      {
        name: "preferredContactChannel",
        label: "Canale preferito",
        type: "select",
        options: ["Telefono", "WhatsApp", "Email", "SMS", "PEC", "Nessuna preferenza"],
      },
      {
        name: "preferredContactTime",
        label: "Fascia oraria preferita",
        type: "select",
        options: ["Mattina", "Pausa pranzo", "Pomeriggio", "Sera", "Qualsiasi"],
      },
      { name: "addressStreet", label: "Indirizzo", wide: true },
      { name: "addressCity", label: "Comune" },
      { name: "addressPostalCode", label: "CAP" },
      { name: "addressProvince", label: "Provincia" },
    ],
  },
  {
    title: "Privacy e comunicazioni",
    description: "Consensi, basi di contatto e limitazioni richieste dal nominativo.",
    fields: [
      {
        name: "privacyLegalBasis",
        label: "Base giuridica",
        type: "select",
        options: ["Consenso", "Esecuzione contratto", "Misure precontrattuali", "Legittimo interesse", "Obbligo legale", "Da verificare"],
      },
      { name: "privacyConsentDate", label: "Data consenso", type: "date" },
      { name: "privacyNoticeVersion", label: "Versione informativa" },
      { name: "allowPhone", label: "Consenso telefonate", type: "checkbox" },
      { name: "allowEmail", label: "Consenso email", type: "checkbox" },
      { name: "allowMessaging", label: "Consenso messaggistica", type: "checkbox" },
      { name: "allowMarketing", label: "Consenso marketing", type: "checkbox" },
      { name: "doNotContact", label: "Non contattare", type: "checkbox" },
      { name: "privacyRevocationDate", label: "Data revoca", type: "date" },
      { name: "privacyNotes", label: "Note privacy", type: "textarea", wide: true },
    ],
  },
  {
    title: "Documenti e sviluppo",
    description: "Documenti identificativi, note operative e prossimo contatto.",
    fields: [
      {
        name: "identityDocumentType",
        label: "Tipo documento",
        type: "select",
        options: ["Carta d’identità", "Passaporto", "Patente", "Altro"],
      },
      { name: "identityDocumentNumber", label: "Numero documento" },
      { name: "identityDocumentExpiry", label: "Scadenza documento", type: "date" },
      { name: "identityDocumentIssuer", label: "Ente rilasciante" },
      { name: "nextContactDate", label: "Data prossimo contatto", type: "date" },
      { name: "nextContactTime", label: "Ora prossimo contatto", type: "time" },
      { name: "nextContactReason", label: "Motivo ricontatto", wide: true },
      { name: "contactNotes", label: "Note anagrafica", type: "textarea", wide: true },
    ],
  },
];

export const contactFilterSections: StructuredFormSection[] = [
  {
    title: "Ricerca nominativo",
    fields: [
      { name: "firstName", label: "Nome" },
      { name: "lastName", label: "Cognome" },
      { name: "companyName", label: "Azienda" },
      { name: "phone", label: "Telefono", type: "tel" },
      { name: "email", label: "Email", type: "email" },
      { name: "taxCode", label: "Codice fiscale" },
      {
        name: "primaryRole",
        label: "Ruolo",
        type: "select",
        options: ["", "Generico", "Proprietario", "Acquirente", "Locatore", "Locatario", "Inserzionista", "Segnalatore", "Professionista"],
      },
      {
        name: "contactStatus",
        label: "Stato",
        type: "select",
        options: ["", "Nuovo", "Da qualificare", "Attivo", "Da ricontattare", "Non interessato", "Sospeso", "Archiviato"],
      },
    ],
  },
  {
    title: "Gestione e ricontatto",
    fields: [
      { name: "acquisitionSource", label: "Provenienza" },
      { name: "assignedAgent", label: "Operatore" },
      { name: "tag", label: "Etichetta" },
      { name: "nextContactFrom", label: "Ricontatto dal", type: "date" },
      { name: "nextContactTo", label: "Ricontatto al", type: "date" },
      { name: "hasPrivacyConsent", label: "Con consenso privacy", type: "checkbox" },
      { name: "includeDoNotContact", label: "Includi non contattare", type: "checkbox" },
    ],
  },
];

export const requestFormSections: StructuredFormSection[] = [
  {
    title: "Cliente e stato",
    fields: [
      { name: "contactId", label: "Cliente o nominativo", required: true, wide: true },
      {
        name: "managementType",
        label: "Tipo gestione",
        type: "select",
        required: true,
        options: ["Acquisto", "Affitto", "Acquisto o affitto"],
      },
      {
        name: "requestStatus",
        label: "Stato richiesta",
        type: "select",
        options: ["Nuova", "Da qualificare", "Qualificata", "Proposte inviate", "Visita", "Trattativa", "Sospesa", "Chiusa"],
      },
      { name: "assignedAgent", label: "Agente assegnato" },
      { name: "priority", label: "Priorità", type: "select", options: ["Bassa", "Normale", "Alta", "Urgente"] },
      { name: "validFrom", label: "Valida dal", type: "date" },
      { name: "validUntil", label: "Valida fino al", type: "date" },
    ],
  },
  {
    title: "Criteri ottimali",
    description: "Caratteristiche che descrivono la soluzione ideale.",
    fields: [
      { name: "preferredPropertyTypes", label: "Tipologie ottimali", placeholder: "Es. appartamento, attico", wide: true },
      { name: "preferredAreas", label: "Zone ottimali", placeholder: "Comuni, quartieri o vie", wide: true },
      { name: "preferredCondition", label: "Stato conservazione ottimale" },
      { name: "preferredMinimumArea", label: "Superficie ottimale minima", type: "number" },
      { name: "preferredRooms", label: "Locali ottimali", type: "number" },
      { name: "preferredFloor", label: "Piano ottimale" },
      { name: "preferredMoveInDate", label: "Disponibilità desiderata", type: "date" },
    ],
  },
  {
    title: "Criteri tollerati",
    description: "Alternative ammissibili da includere nel matching.",
    fields: [
      { name: "acceptedPropertyTypes", label: "Tipologie tollerate", wide: true },
      { name: "acceptedAreas", label: "Zone tollerate", wide: true },
      { name: "acceptedConditions", label: "Stati conservazione tollerati", wide: true },
      { name: "minimumArea", label: "Superficie minima assoluta", type: "number" },
      { name: "minimumRooms", label: "Locali minimi", type: "number" },
      { name: "maximumFloorWithoutElevator", label: "Piano massimo senza ascensore", type: "number" },
      { name: "allowOccupiedProperty", label: "Accetta immobile occupato", type: "checkbox" },
      { name: "allowAuctionProperty", label: "Accetta immobili in asta", type: "checkbox" },
    ],
  },
  {
    title: "Budget e sostenibilità",
    fields: [
      { name: "minimumBudget", label: "Budget minimo", type: "number" },
      { name: "maximumBudget", label: "Budget massimo", type: "number", required: true },
      { name: "maximumMonthlyRent", label: "Canone mensile massimo", type: "number" },
      { name: "maximumCondominiumFees", label: "Spese condominiali massime", type: "number" },
      { name: "availableDeposit", label: "Capitale disponibile", type: "number" },
      { name: "mortgageAmount", label: "Mutuo previsto", type: "number" },
      {
        name: "mortgageStatus",
        label: "Stato mutuo",
        type: "select",
        options: ["Non necessario", "Da valutare", "Pre-delibera richiesta", "Pre-delibera ottenuta", "Deliberato"],
      },
    ],
  },
  {
    title: "Accessori e vincoli",
    fields: [
      { name: "requiredAccessories", label: "Accessori indispensabili", placeholder: "Es. ascensore, box, terrazzo", wide: true },
      { name: "preferredAccessories", label: "Accessori graditi", wide: true },
      { name: "excludedFeatures", label: "Caratteristiche escluse", wide: true },
      { name: "petsAllowedRequired", label: "Animali ammessi indispensabile", type: "checkbox" },
      { name: "accessibleRequired", label: "Accessibilità indispensabile", type: "checkbox" },
      { name: "parkingRequired", label: "Posto auto indispensabile", type: "checkbox" },
      { name: "requestNotes", label: "Note richiesta", type: "textarea", wide: true },
    ],
  },
];

export const activityFormSections: StructuredFormSection[] = [
  {
    title: "Attività",
    fields: [
      {
        name: "activityType",
        label: "Tipo attività",
        type: "select",
        required: true,
        options: ["Telefonata", "Appuntamento", "Visita immobile", "Email", "WhatsApp", "Promemoria", "Censimento", "Nota"],
      },
      { name: "title", label: "Titolo", required: true, wide: true },
      { name: "contactId", label: "Cliente o proprietario" },
      { name: "propertyId", label: "Immobile" },
      { name: "requestId", label: "Richiesta collegata" },
      { name: "assignedOperator", label: "Operatore", required: true },
      {
        name: "activityStatus",
        label: "Stato",
        type: "select",
        options: ["Da confermare", "Confermata", "In corso", "Completata", "Sospesa", "Annullata"],
      },
    ],
  },
  {
    title: "Data e luogo",
    fields: [
      { name: "startDate", label: "Data inizio", type: "date", required: true },
      { name: "startTime", label: "Ora inizio", type: "time", required: true },
      { name: "endDate", label: "Data fine", type: "date" },
      { name: "endTime", label: "Ora fine", type: "time" },
      { name: "isAllDay", label: "Tutto il giorno", type: "checkbox" },
      { name: "location", label: "Luogo", wide: true },
      { name: "meetingLink", label: "Link riunione", wide: true },
    ],
  },
  {
    title: "Ricorrenza e promemoria",
    fields: [
      {
        name: "recurrenceFrequency",
        label: "Ricorrenza",
        type: "select",
        options: ["Nessuna", "Giornaliera", "Settimanale", "Mensile", "Annuale"],
      },
      { name: "recurrenceInterval", label: "Ripeti ogni", type: "number" },
      { name: "recurrenceEndDate", label: "Fine ricorrenza", type: "date" },
      { name: "reminderMinutes", label: "Promemoria prima (minuti)", type: "number" },
      { name: "notifyParticipants", label: "Avvisa i partecipanti", type: "checkbox" },
      { name: "showInCalendar", label: "Visualizza in agenda", type: "checkbox" },
    ],
  },
  {
    title: "Esito e seguito",
    fields: [
      { name: "participants", label: "Altri partecipanti", wide: true },
      { name: "outcome", label: "Esito", wide: true },
      { name: "notes", label: "Note", type: "textarea", wide: true },
      { name: "nextStep", label: "Prossimo passo", wide: true },
      { name: "nextStepDate", label: "Data prossimo passo", type: "date" },
      { name: "nextStepTime", label: "Ora prossimo passo", type: "time" },
    ],
  },
];

export const censusContactFormSections: StructuredFormSection[] = [
  {
    title: "Percorso territoriale",
    description: "Collocazione gerarchica del contatto censito.",
    fields: [
      { name: "area", label: "Zona", required: true },
      { name: "street", label: "Via", required: true, wide: true },
      { name: "streetNumber", label: "Civico", required: true },
      { name: "buildingName", label: "Palazzo o complesso" },
      { name: "staircase", label: "Scala" },
      { name: "internalNumber", label: "Interno" },
      { name: "floor", label: "Piano" },
      {
        name: "surveyExtent",
        label: "Estensione censimento",
        type: "select",
        options: ["Intero edificio", "Parte di edificio", "Unità immobiliare"],
      },
    ],
  },
  {
    title: "Unità immobiliare",
    fields: [
      { name: "propertyLabel", label: "Descrizione immobile", required: true, wide: true },
      {
        name: "propertyType",
        label: "Tipologia",
        type: "select",
        options: ["Appartamento", "Attico", "Villa", "Casa indipendente", "Box", "Negozio", "Ufficio", "Magazzino", "Terreno", "Altro"],
      },
      { name: "commercialArea", label: "Superficie (m²)", type: "number" },
      { name: "rooms", label: "Locali", type: "number" },
      {
        name: "occupancyStatus",
        label: "Occupazione",
        type: "select",
        options: ["Sconosciuta", "Libero", "Occupato dal proprietario", "Locato", "In disuso"],
      },
      { name: "hasElevator", label: "Ascensore", type: "checkbox" },
      { name: "propertyNotes", label: "Note immobile", type: "textarea", wide: true },
    ],
  },
  {
    title: "Dati catastali ed energetici",
    fields: [
      { name: "cadastralSheet", label: "Foglio" },
      { name: "cadastralParcel", label: "Particella" },
      { name: "cadastralSubaltern", label: "Subalterno" },
      { name: "cadastralCategory", label: "Categoria catastale" },
      { name: "cadastralRooms", label: "Vani catastali", type: "number" },
      { name: "cadastralIncome", label: "Rendita catastale", type: "number" },
      {
        name: "energyClass",
        label: "Classe energetica",
        type: "select",
        options: ["Non disponibile", "A4", "A3", "A2", "A1", "B", "C", "D", "E", "F", "G", "Esente"],
      },
    ],
  },
  {
    title: "Proprietario o referente",
    fields: [
      { name: "ownerFirstName", label: "Nome", required: true },
      { name: "ownerLastName", label: "Cognome", required: true },
      { name: "ownerTaxCode", label: "Codice fiscale" },
      { name: "ownershipShare", label: "Quota di proprietà (%)", type: "number" },
      {
        name: "contactRole",
        label: "Ruolo",
        type: "select",
        required: true,
        options: ["Proprietario", "Comproprietario", "Familiare", "Amministratore", "Inquilino", "Portiere", "Referente", "Altro"],
      },
      { name: "primaryPhone", label: "Telefono principale", type: "tel" },
      { name: "secondaryPhone", label: "Telefono secondario", type: "tel" },
      { name: "email", label: "Email", type: "email" },
      {
        name: "preferredContactChannel",
        label: "Canale preferito",
        type: "select",
        options: ["Telefono", "WhatsApp", "Email", "Nessuna preferenza"],
      },
    ],
  },
  {
    title: "Esito censimento e ricontatto",
    fields: [
      {
        name: "surveyStatus",
        label: "Stato censimento",
        type: "select",
        options: ["Da verificare", "Contatto individuato", "Contattato", "Da ricontattare", "Interessato", "Non interessato", "Dati confermati"],
      },
      {
        name: "propertyInterest",
        label: "Possibile interesse",
        type: "select",
        options: ["Sconosciuto", "Valutazione", "Vendita", "Affitto", "Acquisto", "Nessun interesse"],
      },
      { name: "surveyDate", label: "Data censimento", type: "date", required: true },
      { name: "surveyOperator", label: "Operatore", required: true },
      { name: "informationSource", label: "Fonte informazione" },
      { name: "dataReliability", label: "Affidabilità dati", type: "select", options: ["Bassa", "Media", "Alta", "Verificata"] },
      { name: "nextContactDate", label: "Data ricontatto", type: "date" },
      { name: "nextContactTime", label: "Ora ricontatto", type: "time" },
      { name: "nextContactReason", label: "Motivo ricontatto", wide: true },
      { name: "surveyNotes", label: "Note censimento", type: "textarea", wide: true },
    ],
  },
  {
    title: "Privacy",
    fields: [
      {
        name: "privacyLegalBasis",
        label: "Base giuridica del contatto",
        type: "select",
        options: ["Consenso", "Legittimo interesse", "Misure precontrattuali", "Da verificare"],
      },
      { name: "privacyNoticeProvided", label: "Informativa fornita", type: "checkbox" },
      { name: "allowPhone", label: "Consenso telefonate", type: "checkbox" },
      { name: "allowMessaging", label: "Consenso messaggistica", type: "checkbox" },
      { name: "allowEmail", label: "Consenso email", type: "checkbox" },
      { name: "doNotContact", label: "Non contattare", type: "checkbox" },
      { name: "privacyRecordedAt", label: "Data registrazione privacy", type: "date" },
    ],
  },
];
